"use client";

import { Check, Copy, Download, Loader2, Sparkles } from "lucide-react";
import { useTranslations } from "next-intl";
import { useCallback, useEffect, useMemo, useState } from "react";

import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Textarea } from "@/components/ui/textarea";
import { useCreditUsage } from "@/hooks/useCreditUsage";
import { createExportFileName } from "@/lib/workflow-export";
import type { WorkflowStep } from "../../../types";

type ProposalDraftStep = {
  step: WorkflowStep;
  outputDraft: string;
};

type ProposalDraftEngineProps = {
  steps: ProposalDraftStep[];
  workflowRunId: string;
  workflowTitle: string;
};

function getStorageKey(workflowRunId: string) {
  return `root-access:proposal-draft:${workflowRunId}`;
}

function readSavedDraft(workflowRunId: string) {
  if (typeof window === "undefined") {
    return "";
  }

  try {
    return window.localStorage.getItem(getStorageKey(workflowRunId)) ?? "";
  } catch {
    return "";
  }
}

function downloadTextFile({
  content,
  fileName,
  mimeType,
}: {
  content: string;
  fileName: string;
  mimeType: string;
}) {
  const blob = new Blob([content], { type: mimeType });
  const url = window.URL.createObjectURL(blob);
  const link = document.createElement("a");

  link.href = url;
  link.download = fileName;
  document.body.appendChild(link);
  link.click();
  link.remove();
  window.setTimeout(() => window.URL.revokeObjectURL(url), 0);
}

function createDraftPrompt(steps: ProposalDraftStep[]) {
  const stepNotes = steps
    .map(({ outputDraft, step }) =>
      [
        `Micro-step ${step.id}: ${step.title}`,
        `Goal: ${step.goal}`,
        "Output:",
        outputDraft.trim() || "(No saved output)",
      ].join("\n"),
    )
    .join("\n\n---\n\n");

  return [
    "Create an editable Startup Proposal Draft from these Root Access micro-step outputs.",
    "Use these sections exactly: Problem, Target Customer, Validation, Market Segment, Revenue Model, Competitive Difference, MVP Scope.",
    "Keep it clean, structured, concise, and suitable as a working draft for a student to revise.",
    "Use short paragraphs or bullets. Do not write a final submission-ready essay.",
    "Mark missing evidence or uncertain claims with [VERIFY].",
    "Micro-step outputs:",
    stepNotes,
  ].join("\n\n");
}

function toTextDraft(markdownDraft: string) {
  return markdownDraft
    .replace(/^#{1,6}\s+/gm, "")
    .replace(/\*\*/g, "")
    .trim();
}

export function ProposalDraftEngine({
  steps,
  workflowRunId,
  workflowTitle,
}: ProposalDraftEngineProps) {
  const t = useTranslations("ProposalDraftEngine");
  const storageKey = useMemo(
    () => getStorageKey(workflowRunId),
    [workflowRunId],
  );
  const [draft, setDraft] = useState(() => readSavedDraft(workflowRunId));
  const [isGenerating, setIsGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [isCopied, setIsCopied] = useState(false);
  const [hasAutoGenerated, setHasAutoGenerated] = useState(
    () => readSavedDraft(workflowRunId).trim().length > 0,
  );
  const draftPrompt = useMemo(() => createDraftPrompt(steps), [steps]);
  const hasDraft = draft.trim().length > 0;
  const { canUse, getRemaining, recordUse } = useCreditUsage();

  useEffect(() => {
    try {
      if (hasDraft) {
        window.localStorage.setItem(storageKey, draft);
      } else {
        window.localStorage.removeItem(storageKey);
      }
    } catch {
      return;
    }
  }, [draft, hasDraft, storageKey]);

  const generateDraft = useCallback(async () => {
    if (!canUse("proposalDraft")) {
      setError(t("limitReached"));
      setHasAutoGenerated(true);
      return;
    }

    setError(null);
    setIsGenerating(true);

    try {
      const response = await fetch("/api/gemini/generate", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ prompt: draftPrompt }),
      });
      const data = (await response.json()) as {
        message?: unknown;
        output?: unknown;
      };

      if (!response.ok) {
        throw new Error(
          typeof data.message === "string" ? data.message : t("error"),
        );
      }

      if (typeof data.output !== "string" || data.output.trim().length === 0) {
        throw new Error(t("empty"));
      }

      recordUse("proposalDraft");
      setDraft(data.output.trim());
    } catch (draftError) {
      setError(draftError instanceof Error ? draftError.message : t("error"));
    } finally {
      setIsGenerating(false);
      setHasAutoGenerated(true);
    }
  }, [canUse, draftPrompt, recordUse, t]);

  useEffect(() => {
    if (hasAutoGenerated || hasDraft || isGenerating) {
      return;
    }

    const timer = window.setTimeout(() => {
      void generateDraft();
    }, 0);

    return () => window.clearTimeout(timer);
  }, [generateDraft, hasAutoGenerated, hasDraft, isGenerating]);

  async function copyDraft() {
    await navigator.clipboard.writeText(draft);
    setIsCopied(true);
    window.setTimeout(() => setIsCopied(false), 1600);
  }

  function downloadDraft(format: "markdown" | "text") {
    const isMarkdown = format === "markdown";

    downloadTextFile({
      content: isMarkdown ? draft : toTextDraft(draft),
      fileName: createExportFileName(
        `${workflowTitle}-proposal-draft`,
        isMarkdown ? "md" : "txt",
      ),
      mimeType: isMarkdown
        ? "text/markdown;charset=utf-8"
        : "text/plain;charset=utf-8",
    });
  }

  return (
    <Card className="rounded-lg border-primary/20 bg-background py-5 shadow-sm transition-shadow hover:shadow-md">
      <CardHeader className="gap-4 sm:flex-row sm:items-start sm:justify-between">
        <div className="space-y-2">
          <CardTitle className="text-xl">{t("title")}</CardTitle>
          <CardDescription className="text-sm leading-6">
            {t("description")}
          </CardDescription>
        </div>
        <Button
          type="button"
          className="h-10 w-full sm:w-auto"
          disabled={isGenerating}
          onClick={generateDraft}
        >
          {isGenerating ? (
            <Loader2 aria-hidden="true" className="animate-spin" />
          ) : (
            <Sparkles aria-hidden="true" />
          )}
          {isGenerating ? t("generating") : t("regenerate")}
        </Button>
      </CardHeader>
      <CardContent className="grid gap-4">
        {error ? (
          <p className="rounded-lg border border-destructive/30 bg-destructive/10 px-3 py-2 text-sm leading-6 text-destructive">
            {error}
          </p>
        ) : null}
        <p className="text-xs leading-5 text-muted-foreground">
          {t("remaining", {
            drafts: String(getRemaining("proposalDraft")),
          })}
        </p>
        <Textarea
          aria-label={t("title")}
          className="min-h-80 resize-y rounded-lg bg-muted/30 text-sm leading-6 text-foreground"
          placeholder={isGenerating ? t("generating") : t("placeholder")}
          value={draft}
          onChange={(event) => setDraft(event.target.value)}
        />
        <div className="flex flex-col gap-2 sm:flex-row sm:flex-wrap">
          <Button
            type="button"
            variant="outline"
            className="h-10 justify-center"
            disabled={!hasDraft}
            onClick={copyDraft}
          >
            {isCopied ? <Check aria-hidden="true" /> : <Copy aria-hidden="true" />}
            {isCopied ? t("copied") : t("copy")}
          </Button>
          <Button
            type="button"
            variant="outline"
            className="h-10 justify-center"
            disabled={!hasDraft}
            onClick={() => downloadDraft("markdown")}
          >
            <Download aria-hidden="true" />
            {t("downloadMarkdown")}
          </Button>
          <Button
            type="button"
            variant="outline"
            className="h-10 justify-center"
            disabled={!hasDraft}
            onClick={() => downloadDraft("text")}
          >
            <Download aria-hidden="true" />
            {t("downloadText")}
          </Button>
        </div>
      </CardContent>
    </Card>
  );
}
